		[types.wood_type.quark]
			azalea = true
			ancient = false
			blossom = true

		[types.wood_type.regions_unexplored]
			alpha = false
			baobab = true
			blackwood = true
			brimwood = true
			cobalt = true
			cypress = true
			dead = false
			eucalyptus = true
			joshua = true
			kapok = true
			larch = true
			magnolia = true
			maple = true
			palm = true
			pine = true
			redwood = true
			socotra = true
			willow = true
			wisteria = true
			pink_bioshroom = true
			yellow_bioshroom = true
			blue_bioshroom = true
			green_bioshroom = true

		[types.wood_type.domum_ornamentum]
			cactus = true
			cactus_extra = true

		[types.wood_type.environmental]
			willow = true
			pine = true
			plum = true
			wisteria = true

		[types.wood_type.minecraft]
			pale_oak = false

		[types.wood_type.autumnity]
			maple = true

		[types.leaves_type.quark]
			ancient = false
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.regions_unexplored]
			alpha = false
			apple_oak = false
			ashen = false
			bamboo = true
			baobab = true
			blackwood = true
			blue_magnolia = true
			brimwood = false
			cypress = true
			dead_pine = false
			dead = false
			eucalyptus = true
			flowering = true
			golden_larch = true
			kapok = true
			larch = true
			magnolia = true
			maple = true
			orange_maple = false
			palm = true
			pine = true
			pink_magnolia = true
			red_maple = false
			redwood = true
			silver_birch = true
			small_oak = false
			socotra = true
			white_magnolia = true
			willow = true
			sky_wisteria = true
			lavender_wisteria = true
			salmon_wisteria = true

		[types.leaves_type.environmental]
			pink_wisteria = true
			blue_wisteria = true
			purple_wisteria = true
			white_wisteria = true
			hibiscus = true
			willow = true
			pine = true
			plum = true
			cheerful_plum = true
			moody_plum = true
			wisteria = true

		[types.leaves_type.minecraft]
			pale_oak = false

		[types.leaves_type.chipped]
			apple_acacia = true
			cherry_acacia = true
			dead_acacia = true
			frosted_acacia = true
			golden_acacia = true
			golden_apple_acacia = true
			golden_cherry_acacia = true
			magenta_flower_acacia = true
			orange_acacia = true
			red_acacia = true
			white_flower_acacia = true
			apple_birch = true
			cherry_birch = true
			dead_birch = true
			frosted_birch = true
			golden_birch = true
			golden_apple_birch = true
			golden_cherry_birch = true
			magenta_flower_birch = true
			orange_birch = true
			red_birch = true
			white_flower_birch = true
			apple_dark_oak = true
			cherry_dark_oak = true
			dead_dark_oak = true
			frosted_dark_oak = true
			golden_dark_oak = true
			golden_apple_dark_oak = true
			golden_cherry_dark_oak = true
			magenta_flower_dark_oak = true
			orange_dark_oak = true
			red_dark_oak = true
			white_flower_dark_oak = true
			apple_jungle = true
			cherry_jungle = true
			dead_jungle = true
			frosted_jungle = true
			golden_jungle = true
			golden_apple_jungle = true
			golden_cherry_jungle = true
			magenta_flower_jungle = true
			orange_jungle = true
			red_jungle = true
			white_flower_jungle = true
			apple_oak = true
			cherry_oak = true
			dead_oak = true
			frosted_oak = true
			golden_oak = true
			golden_apple_oak = true
			golden_cherry_oak = true
			magenta_flower_oak = true
			orange_oak = true
			red_oak = true
			white_flower_oak = true
			apple_spruce = true
			cherry_spruce = true
			dead_spruce = true
			frosted_spruce = true
			golden_spruce = true
			golden_apple_spruce = true
			golden_cherry_spruce = true
			magenta_flower_spruce = true
			orange_spruce = true
			red_spruce = true
			white_flower_spruce = true

		[types.leaves_type.autumnity]
			maple = true
			yellow_maple = true
			orange_maple = true
			red_maple = true

		[types.lantern.suppsquared]
			copper_lantern = true
			brass_lantern = true
			crimson_lantern = true

		[types.lantern.chipped]
			blue_paper_lantern = true
			burning_coal_lantern = true
			checkered_iron_lantern = true
			dark_blue_paper_lantern = true
			ender_lantern = true
			green_paper_lantern = true
			iron_bowl_lantern = true
			purple_paper_lantern = true
			red_paper_lantern = true
			small_green_lantern = true
			white_paper_lantern = true
			wooden_cage_lantern = true
			wrought_iron_lantern = true
			yellow_tube_lantern = true
			blue_paper_soul_lantern = true
			blue_tube_soul_lantern = true
			checkered_iron_soul_lantern = true
			golden_paper_soul_lantern = true
			gray_paper_soul_lantern = true
			iron_bowl_soul_lantern = true
			lime_paper_soul_lantern = true
			orange_paper_soul_lantern = true
			small_red_soul_lantern = true
			wooden_cage_soul_lantern = true
			yellow_paper_soul_lantern = true

		[entries.wood_type.quark]
			vertical_planks = false
			post = true
			chest = true
			stripped_post = true
			ladder = true
			trapped_chest = true
			bookshelf = false
			hollow_log = true
			vertical_slab = true

		[entries.wood_type.regions_unexplored]
			branch = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.mcwbridges]
			bridge_pier = true
			rope_bridge = true
			log_bridge_middle = true
			rope_bridge_stair = true
			log_bridge_stair = true
			rail_bridge = true

		[entries.wood_type.mcwfences]
			highley_gate = true
			picket_fence = true
			stockade_fence = true
			wired_fence = true
			horse_fence = true
			pyramid_gate = true

		[entries.wood_type.mcwfurnitures]
			stripped_glass_table = true
			stripped_desk = true
			stripped_double_kitchen_cabinet = true
			end_table = true
			stool_chair = true
			stripped_kitchen_sink = true
			stripped_lower_triple_drawer = true
			stripped_drawer_counter = true
			bookshelf_drawer = true
			double_drawer = true
			stripped_coffee_table = true
			stripped_counter = true
			stripped_striped_chair = true
			covered_desk = true
			stripped_stool_chair = true
			stripped_modern_wardrobe = true
			cupboard_counter = true
			stripped_covered_desk = true
			stripped_kitchen_cabinet = true
			coffee_table = true
			glass_table = true
			stripped_cupboard_counter = true
			stripped_triple_drawer = true
			stripped_chair = true
			stripped_double_drawer_counter = true
			stripped_modern_desk = true
			stripped_bookshelf_cupboard = true
			modern_wardrobe = true
			lower_bookshelf_drawer = true
			striped_chair = true
			double_kitchen_cabinet = true
			stripped_large_drawer = true
			wardrobe = true
			kitchen_sink = true
			modern_desk = true
			stripped_lower_bookshelf_drawer = true
			stripped_end_table = true
			drawer = true
			stripped_bookshelf_drawer = true
			stripped_glass_kitchen_cabinet = true
			stripped_bookshelf = true
			modern_chair = true
			chair = true
			stripped_table = true
			double_drawer_counter = true
			drawer_counter = true
			kitchen_cabinet = true
			counter = true
			stripped_modern_chair = true
			bookshelf_cupboard = true
			table = true
			desk = true
			stripped_double_wardrobe = true
			stripped_double_drawer = true
			triple_drawer = true
			lower_triple_drawer = true
			glass_kitchen_cabinet = true
			bookshelf = true
			stripped_wardrobe = true
			large_drawer = true
			double_wardrobe = true
			stripped_drawer = true

		[entries.wood_type.mcwpaths]
			planks_path = true

		[entries.wood_type.mcwwindows]
			louvered_shutter = true
			plank_pane_window = true
			curtain_rod = true
			plank_four_window = true
			stripped_log_window2 = true
			log_parapet = true
			window2 = true
			stripped_log_four_window = true
			stripped_log_window = true
			plank_window = true
			plank_window2 = true
			pane_window = true
			stripped_pane_window = true
			four_window = true
			plank_parapet = true
			blinds = true
			window = true
			shutter = true

		[entries.leaves_type.quark]
			hedge = false
			leaf_carpet = true

		[entries.leaves_type.regions_unexplored]
			shrub = true

		[entries.leaves_type.mcwfences]
			hedge = true
