name = "Goliath Gaming 2026"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "929beffdd6ff98bb576daf126ebd0a7ab985ed3e2036e4bbab9834d35bc11b73"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
