name = "GG 1.21.1 Export Test"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f2fdc7e3163f6023337ac2e349a9068aa5881f4b621b0e7b38d7f9b5cef32c1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
