name = "Goliath Gaming 2025"
author = "MegaJohnny"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8886fdecf50047d1965d06d7d2209be8f3b1b5bd28b482f36827b4569a084809"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
