name = "Goliath Gaming 2025"
author = "MegaJohnny"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c2b3b9d7510a7ad4895dcc5532f6413a46f9c9d3b10ba3bfcd453fcdb6fd312"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
