name = "Goliath Gaming 2025"
author = "MegaJohnny"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90b14acfac710c94e7b7bfa30ed6644d0ef9aa4a1c1a3ff81dab644e70a1cccd"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
