name = "GG 1.21.1 Export Test"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee4a6b1a01d878413daa3edb4d0b36a710ea452ec1ede7b631c3ddf3bf4576c8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
